spring.datasource.url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=UTC&useSSL=false
spring.datasource.username: root
spring.datasource.password: TestTest
spring.jpa.show-sql: false
spring.jpa.generate-ddl: false
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.open-in-view: false

spring.flyway:
  baselineOnMigrate: true


blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 921 782-33-57
  email: kjanni22@gmail.com
  copyright: Кочеткова Евгения
  copyrightFrom: 2020

db:
  captcha:
    lifetime: 60