spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blogdb?useUnicode=true&characterEncoding=utf-8&reconnect=true&useSSL=false&serverTimezone=UTC}
    username: root
    password: TestTest

  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: validate

  http:
    multipart:
      maxSwallowSize: 5Mb

  flyway:
    baselineOnMigrate: true

  mail:
    protocol: smtps
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 465

server:
  port: ${PORT:8080}

mail:
  debug: true



blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 921 782-33-57
  email: kjanni22@gmail.com
  copyright: Кочеткова Евгения
  copyrightFrom: 2020
  post:
    title:
      length:
        min: 3
    text:
      length:
        min: 50
    comment:
      text:
        length:
          min: 0
  address: ${LOCAL:https://blog-skillbox.herokuapp.com}

captcha:
  lifetime: 60
  scheduledRate: 3600000
  width: 100
  height: 35
  length: 26
  wordLength: 5

photo:
  avatarPath: upload/avatars
  width: 36
  height: 36
  postImg:
    path: upload/images
    nameSize: 5
    subfolderSize: 2

password:
  length:
    min: 6