spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=UTC&useSSL=false
    username: root
    password: TestTest

  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: validate

  http:
    multipart:
      maxSwallowSize: 5Mb

  flyway:
    baselineOnMigrate: true


blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 921 782-33-57
  email: kjanni22@gmail.com
  copyright: Кочеткова Евгения
  copyrightFrom: 2020
  post:
    title:
      length:
        min: 3
    text:
      length:
        min: 50

captcha:
  lifetime: 60
  scheduledRate: 3600000
  width: 100
  height: 35
  length: 26
  wordLength: 5

photo:
  path: avatar

password:
  length:
    min: 6