INSERT INTO `blogdb`.`posts`
(`id`,
`is_active`,
`moderation_status`,
`title`,
`time`,
`text`,
`view_count`,
`moderator_id`,
`user_id`)
VALUES
(12,
0,
'NEW',
'Inactive 2 post',
'2020-02-02 07:00:00.000000',
'Rain Man is a 1988 American road comedy-drama film directed by Barry Levinson and written by Barry Morrow and Ronald Bass. It tells the story of abrasive, selfish young wheeler-dealer Charlie Babbitt (Tom Cruise), who discovers that his estranged father has died and bequeathed virtually all of his multi-million dollar estate to his other son, Raymond (Dustin Hoffman), an autistic savant, of whose existence Charlie was unaware. Charlie is left with only his father beloved vintage car and rosebushes. Valeria Golino also stars as Charlie girlfriend Susanna.',
10,
1,
1),
(13,
0,
'NEW',
'Inactive post',
'2020-01-30 07:00:00.000000',
'Rain Man is a 1988 American road comedy-drama film directed by Barry Levinson and written by Barry Morrow and Ronald Bass. It tells the story of abrasive, selfish young wheeler-dealer Charlie Babbitt (Tom Cruise), who discovers that his estranged father has died and bequeathed virtually all of his multi-million dollar estate to his other son, Raymond (Dustin Hoffman), an autistic savant, of whose existence Charlie was unaware. Charlie is left with only his father beloved vintage car and rosebushes. Valeria Golino also stars as Charlie girlfriend Susanna.',
0,
1,
1),
(14,
1,
'NEW',
'PENDING post',
'2020-01-30 07:00:00.000000',
'Rain Man is a 1988 American road comedy-drama film directed by Barry Levinson and written by Barry Morrow and Ronald Bass. It tells the story of abrasive, selfish young wheeler-dealer Charlie Babbitt (Tom Cruise), who discovers that his estranged father has died and bequeathed virtually all of his multi-million dollar estate to his other son, Raymond (Dustin Hoffman), an autistic savant, of whose existence Charlie was unaware. Charlie is left with only his father beloved vintage car and rosebushes. Valeria Golino also stars as Charlie girlfriend Susanna.',
11,
1,
1),
(15,
1,
'DECLINED',
'DECLINED post',
'2020-03-30 07:00:00.000000',
'Rain Man is a 1988 American road comedy-drama film directed by Barry Levinson and written by Barry Morrow and Ronald Bass. It tells the story of abrasive, selfish young wheeler-dealer Charlie Babbitt (Tom Cruise), who discovers that his estranged father has died and bequeathed virtually all of his multi-million dollar estate to his other son, Raymond (Dustin Hoffman), an autistic savant, of whose existence Charlie was unaware. Charlie is left with only his father beloved vintage car and rosebushes. Valeria Golino also stars as Charlie girlfriend Susanna.',
10,
1,
1),
(16,
1,
'ACCEPTED',
'ACCEPTED post',
'2020-03-30 07:00:00.000000',
'Rain Man is a 1988 American road comedy-drama film directed by Barry Levinson and written by Barry Morrow and Ronald Bass. It tells the story of abrasive, selfish young wheeler-dealer Charlie Babbitt (Tom Cruise), who discovers that his estranged father has died and bequeathed virtually all of his multi-million dollar estate to his other son, Raymond (Dustin Hoffman), an autistic savant, of whose existence Charlie was unaware. Charlie is left with only his father beloved vintage car and rosebushes. Valeria Golino also stars as Charlie girlfriend Susanna.',
10,
1,
1),
(17,
1,
'ACCEPTED',
'ACCEPTED post',
'2020-06-01 10:00:00.000000',
'Rain Man is a 1988 American road comedy-drama film directed by Barry Levinson and written by Barry Morrow and Ronald Bass. It tells the story of abrasive, selfish young wheeler-dealer Charlie Babbitt (Tom Cruise), who discovers that his estranged father has died and bequeathed virtually all of his multi-million dollar estate to his other son, Raymond (Dustin Hoffman), an autistic savant, of whose existence Charlie was unaware. Charlie is left with only his father beloved vintage car and rosebushes. Valeria Golino also stars as Charlie girlfriend Susanna.',
10,
1,
1);

